# docker-compose.yml: use for local docker orchestration.
version: "3"

services:
    node:
        build: .
        command: npm start
        volumes:
            - ./:/app
        environment:
            NPM_INSTALL: ENABLE
        ports:
            - "5000:5000"
        depends_on:
            - db
        links:
            - db

    db:
        image: mysql:5.7
        volumes:
            - ./datadir/mysql:/var/lib/mysql
        container_name: container-db
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: iamthestrongestpassword
            MYSQL_DATABASE: database_wallet